[project]
name = "rdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hy>=1.1.0",
    "rdflib>=7.1.4",
    "rdflib-jsonld>=0.6.2",
]
