[project]
name = "ollama-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hy>=1.1.0",
    "ollama>=0.5.3",
]
