[project]
name = "perplexity-search-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hy>=1.1.0",
    "openai>=1.99.9",
]
