[project]
name = "matplotlib-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hy>=1.1.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
]
