[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hy>=1.1.0",
    "pip>=25.2",
    "spacy>=3.8.7",
]
