[project]
name = "kgn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "collection>=0.1.6",
    "hy>=1.1.0",
    "pip>=25.2",
    "pyinquirer>=1.0.3",
    "requests>=2.32.4",
    "spacy>=3.8.7",
    "textui>=0.2",
]
